[build]
command = "pnpm run build"
publish = "dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/index.html"
[headers.values]
Content-Security-Policy = "default-src 'self'; style-src 'self' https://fonts.googleapis.com/; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://fonts.googleapis.com"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "same-origin"
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/(fonts|icons|backgrounds|emojis)/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/(favicon.ico|robots.txt|sitemap.xml|browserconfig.xml|manifest.webmanifest)"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/infographics/*"
[headers.values]
Cache-Control = "public, max-age=604800, stale-while-revalidate=604800, immutable"

[[headers]]
for = "/**/*.(js|css)"
[headers.values]
Cache-Control = "public, max-age=604800, stale-while-revalidate=604800, immutable"
