import nanoid from 'nanoid';
import { ModalProps } from '../../context/ModalContext';

/* 
Pre-questionaire Message
Hey there, Skykids,

I just wanted to drop a quick note to say thanks for taking your time to write your feedback.

I've been getting a bunch of feedback from those of you who took the time to share, and most of it has been super helpful. It's great to see that the countless hours I've poured into this project are paying off.

I'm always looking for ways to improve the app, so if you have any suggestions, please let me know.

Thanks again for your support!

FAQ
Translation Error? (Button to Google Sheet for translation)
If you know the correct translation, feel free to edit the translation sheet.
You will need to register as a translator, instruction is in the same Google Sheet.

Notification?
Unfortunately, due to iOS lack of support for service notification for PWA, the app will crash when if notification is implemented. 
I will get to implementing it after it is fully supported or at least it won't crash the app when implemented 

Widget Support?
Widget are not supported in PWA.

Incorrect Timing? (Of by an hour)
This is usually caused by changes in your region time or TGC's time, like daylight savings etc.
I will try to compensate for it but it's too much for me to think about.

Other countdowns/timers? (ie Traveling Spirit, Reset, Grandma, etc)
Traveling Spirit: occurs biweekly, starts on Thursday 0000, ends on Sunday 2359
Reset, Geyser, Grandma: Sky Clock by Chris Stead.

Feedback Form Fields
Type of feedback: (select) Bug, Feature Request, Message
Title: (text)
Description: (textarea)
Method of reponse: (select) Email, Discord DM, None
if Email:
  Email Address: (email)
  Nickname: (text)
if Discord DM:
  Discord Username: (text)
  Discord Server: (multi-checkbox) Sky Official, Sky Infographic Database, Nastymold\
*/

/*
Hidden Fields (sent to server)
- Feedback ID generated by nanoid
- App info (branch, commit, locale, timezone)
- Device info (size, locale, timezone, user agent, URL)
- Crash log if applicable
*/

/* Feedback ID
- Generated by nanoid
- Store it in localStorage
  - Check if browser supports localStorage and user has not disabled it
- Used to identify feedback responses when PLutoy published it
*/

/* Feedback System
Submit endpoint:
  POST /api/feedback
  Internally will send the feedback to internal discord server through webhook
  Store in KV store for Plutoy to view
Response endpoint:
  GET /api/feedback/:id/response
  Will return the response from the server


*/

export default function FeedbackModal({ hideModal }: ModalProps) {
  return <FeedbackForm onClose={() => hideModal()} />;
}

interface FeedbackFormProps {
  onClose: () => void;
}

export function FeedbackForm({ onClose }: FeedbackFormProps) {
  return <form></form>;
}
